### ISSUE TITLE
Java interoperation

### ISSUE THREAD

**Issue by josepowera** [outbrain/fwumious_wabbit#25]
Looking forward to a moment when there will be some way to test interoperation with Java - to use at least predict part in Java using JNI/JNA or something similar, the same as we currently use VW maven component (https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/java).

**Comment by andraztori** [comment]
@josepowera Any chance you write the JNI bridge?
It should be fairly straightforward with Rust JNI crate.

**Comment by andraztori** [comment]
@josepowera If you want to test, there is now a "jni" branch with basic JNI support. Want to test it out?

**Comment by josepowera** [comment]
Sure!

**Comment by bbenshalom** [comment]
Hi @josepowera ,
We now have FFI support in the main branch, which than you can use with JNI or with the new project panama API in JDK 19. Please feel free to try it out and let us know if you see any issues. Closing this issue as it is resolved.
