### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by aburkov** [outbrain/fwumious_wabbit#33]
Hey. Do you have a tutorial that explains how to install FW on Linux?

**Comment by andraztori** [comment]
Since we don't provide packages, it's a two step process:
1) install rust compiler by running
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
2) clone this repository
3) in the repository run "cargo build"

this should produce you a fw binary under target/debug/fw

**Comment by yonatankarni** [comment]
just make sure to build in release mode for acceptable performance:
cargo build --release
