### ISSUE TITLE
Tag this repo for hacktoberfest?

### ISSUE THREAD

**Issue by sed-i** [outbrain/fwumious_wabbit#62]
Hi there,
Was wondering if you'd be interested in [tagging](https://hacktoberfest.com/participation/#pr-mr-details) this repo with [`hacktoberfest`](https://github.com/topics/hacktoberfest).

...or tag individual PRs with [`hacktoberfest-accepted`](https://github.com/topics/hacktoberfest-accepted).

**Comment by bbenshalom** [comment]
Hi @sed-i! Unfortunately, this year we have no plan to participate in `hacktoberfest`. We do plan in the near future to make changes to this repo so it is more prepared for such an event. Thanks for the suggestion!
